# Generated by Django 5.0.7 on 2024-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reviewform'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewform',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
