# Generated by Django 5.0.7 on 2024-08-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewform',
            name='study_at',
        ),
    ]
