# Generated by Django 5.0.7 on 2024-08-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_reviewform_study_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewform',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reviewform',
            name='rating',
        ),
    ]
